//
//  ActiveProgramsViewModel.swift
//  SpaceBS
//
//  Created by ONUR BOSTAN on 29.02.2024.
//

import Foundation

class ActiveProgramsViewModel {
    let programs: [ActiveProgramsModel] = [
    ActiveProgramsModel(programsName: "2001 Mars Odyssey", image: "odyssey", title: """
        The 2001 Mars Odyssey is a robotic spacecraft orbiting the planet Mars. The project, which has an estimated cost of $297 million for the entire mission, was developed by NASA and externally contracted to Lockheed Martin. Its mission is to detect evidence of water and ice, past or present, using spectrometers and thermal cameras, as well as to study the planet's geology and radiation environment. It is hoped that the data obtained by Odyssey will help answer the question of whether there is life on Mars and create a risk assessment of radiation that astronauts may be exposed to in the future. It also acts as a relay for communication with Earth between the Curiosity rover and the earlier Mars Exploration Rover and Phoenix lander. It takes its name from the film 2001: A Space Odyssey, written by him and Stanley Kubrick, as a tribute to science fiction writer Arthur C. Clarke.

        Odyssey was launched on a Delta II 7925 rocket from Cape Canaveral Space Force Base Launch Complex 17A on April 7, 2001, and reached Mars orbit at 02:30 UTC on October 24, 2001 (7:30 PM PDT, 10:30 PM EDT on October 23).

        NASA announced on May 28, 2002 (sol 210) that Odyssey's GRS instrument had detected large amounts of hydrogen, a sign that ice must be present within a meter of the planet's surface, and was continuing to map the distribution of water below the shallow surface. The orbiter also discovered enormous deposits of water ice near the surface of equatorial regions.

        As of December 15, 2010, it broke the record for the longest-serving spacecraft on Mars after 3,340 days of activity. Odyssey also served as NASA's main communications vehicle for Mars surface exploration over the last decade, until the Curiosity rover. It is currently the longest survivor in orbit around a planet other than Earth, ahead of the Pioneer Venus Orbiter (which lasted 14 years) and Mars Express (which lasted more than 17 years) at 22 years, 4 months and 1 day. It holds the record for active spacecraft. As of October 2019, it is in a polar orbit with a semimajor axis of approximately 3,800 km (2,400 mi) around Mars. It has enough fuel to operate until 2025.
        """),
    ActiveProgramsModel(programsName: "Cassini-Huygens", image: "cassini", title: """
        Cassini–Huygens was a joint NASA, ESA, and ASI interplanetary space exploration mission launched on October 15, 1997, to study the Saturn system, including its natural moons and rings.

        It is the fourth space probe to visit Saturn and the first to orbit it. The spacecraft, which was launched into space in 1997, after arriving at Saturn in 2004, observed this planet and also Jupiter, examining the heliosphere and many natural satellites for the purpose of relativity theory experiments. The two-piece spacecraft, which takes photographs of the planet, its rings and moons almost every day, collects data and sends them to Earth, takes its name from astronomers Giovanni Domenico Cassini and Christiaan Huygens. Finally, after entering Saturn's rings, capturing and analyzing gas, dust and ice particles and taking high-resolution photographs, its mission is planned to end by entering the planet's atmosphere on September 15, 2017.

        Cassini, which began to be developed in the 1980s, was launched into space on October 15, 1997, with the Titan IVB / Centaur carrier rocket. After 7 years of interplanetary flight, it entered orbit around Saturn on July 1, 2004. On December 25, 2004, at approximately 02:00 UTC, the Huygens satellite separated from the rover and landed on Titan on January 14, 2005.

        One of his greatest discoveries is that there are large sources of liquid water on Saturn's moons Titan, Enceladus and Mimas, and that these moons could potentially harbor life.[10] NASA Planetary Protection Office, which is concerned about Cassini's mission contaminating these waters that may have life at the end of its mission; Considering that some microorganisms might be present in the Cassini spacecraft because it was not cleaned well enough before being launched from Earth, he decided to crash the spacecraft into Saturn.[10] In line with this decision, Cassini, which made a close pass to Titan on April 22, 2017, took advantage of the gravitational power obtained from this maneuver to make 22 dives between Saturn's upper atmosphere and the rings closest to Saturn, thus obtaining closer information about the rings. planned; The first dive was made on April 26.

        After 22 dives following the first dive, it was dropped into the planet's atmosphere at 13:44 on September 15, 2017, and its mission was terminated, as its fuel was exhausted and to avoid damaging satellites with possible life potential.
        """),
    ActiveProgramsModel(programsName: "Chandra X-ray Observatory", image: "chandra", title: "The Chandra X-ray Observatory is a satellite launched on July 23, 1999, by NASA's STS-93 mission. The name of the satellite was given to commemorate Indian-American physicist Subrahmanyan Chandrasekhar, who is known for determining the Chandrasekhar limit for white dwarfs that later turn into neutron stars. Also, Chandra means moon or shining in Sanskrit."),
    ActiveProgramsModel(programsName: "Curiosity", image: "curiosity", title: """
        Curiosity is an automobile-sized Mars rover exploring Mars' Gale crater and Aeolis Mons (the summit of Gale crater) as part of NASA's Mars Science Laboratory (MSL) mission. The word Curiosity means "Curiosity" in Turkish. Curiosity launched from Cape Canaveral (CCAFS) on 26 November 2011 at 15:02:00 UTC and landed at Aeolis Palus inside the Gale crater on Mars on 6 August 2012 at 05:17:57 UTC. The Bradbury landing site was less than 2.4 km (1.5 mi) from the center of the rover's landing target after a journey of 560 million km (350 million mi).

        Mission objectives include investigating the climate and geology of Mars, assessing whether the selected area within Gale crater offers suitable environmental conditions for microbial life (including investigating the role of water), and planetary habitability studies in preparation for human exploration.

        In December 2012, Curiosity's two-year mission was extended indefinitely, and NASA celebrated the fifth anniversary of the Curiosity rover's landing on August 5, 2017. On August 6, 2022, a detailed summary of the Curiosity rover's achievements over the past decade was published. The rover is currently operational and has been active on Mars for 4,111 sols (4,224 total Earth days or 11 years, 6 months, 23 days) since landing as of February 29, 2024.

        The NASA/JPL Mars Science Laboratory/Curiosity Project Team was recognized by the US National Aeronautic Association as "The successful landing of Curiosity on Mars will enhance the nation's technological and engineering capabilities and significantly advance humanity's understanding of the ancient habitable environments of Mars." He was awarded the 2012 Robert J. Collier Award "for his outstanding achievements such as". The design of the Curiosity rover also formed the basis for NASA's 2021 Perseverance mission, which carries different scientific instruments.
        """),
    ActiveProgramsModel(programsName: "Dawn", image: "dawn", title: """
        Dawn was a space probe launched by NASA in September 2007 on a mission to study Vesta and Ceres, two of the three known proto-planets of the asteroid belt. In the ninth mission of NASA's Discovery program, the Dawn spacecraft entered Vesta orbit on July 16, 2011, completing a 14-month exploration mission before departing for Ceres in late 2012. It entered orbit of Ceres on March 6, 2015. In 2017, NASA announced that the planned nine-year mission would be extended until the probe's hydrazine fuel supply was exhausted.[13] NASA announced on November 1, 2018 that Dawn had exhausted its hydrazine fuel and the mission was over. The spacecraft is currently orbiting Ceres in an uncontrolled but stable orbit.

        Dawn orbits two extraterrestrial bodies, visiting Vesta and Ceres, and also orbiting a dwarf planet in March 2015, arriving at Ceres a few months before New Horizons, which will fly past Pluto in July of the same year. It was the first spacecraft to enter.

        The Dawn mission was managed by NASA's Jet Propulsion Laboratory division. NASA's European partners from Italy, Germany, and France contributed to the mission by providing spacecraft parts. This mission was the first NASA exploration mission to use an ion engine, which allowed the spacecraft to orbit and exit two celestial bodies. Previous multi-target missions using chemical engines, such as the Voyager program, were limited to flights only.
        """),
    ActiveProgramsModel(programsName: "Hubble", image: "hubble", title: """
        The Hubble Space Telescope (HUT) is named in memory of American astronomer Edwin Hubble; It is a space telescope carried into orbit around Earth by the Space Shuttle Discovery during Mission STS-31 in April 1990. Although it was not the first space telescope, HUT is one of the largest and has many outstanding features. It is also well-known for being both a vital research tool and an effective public relations tool for astronomy.

        HUT is a joint effort between NASA and the European Space Agency (ESA) and is part of NASA's Great Observatories program, which consists of the Compton Gamma Ray Observatory, Chandra X-ray Observatory, and Spitzer Space Telescope projects.

        The construction of space telescopes was first considered in 1923. Funding was found for HUT in the 1970s, with the goal of sending it into space in 1983, but the project was delayed by technical delays, budget problems and the Challenger disaster. After it was placed into orbit in 1990, scientists found that the main mirror was misplaced, limiting the telescope's operations. This problem was corrected on a space shuttle flight in 1993.

        Thanks to its location outside the Earth's atmosphere, HUT can have many advantages compared to telescopes on the ground: In addition to obtaining images free from the negative effects of the atmosphere (such as blurring in the image and background pollution caused by light reflected from particles in the air), observation of ultraviolet light trapped by the ozone layer can only be achieved. It is possible this way.

        Following its launch in 1990, it has become one of the most important instruments in the history of astronomy. It has been of great help to astronomers in finding solutions to their basic problems in the field of astrophysics. The Hubble ultra-deep field photograph recorded by the Hubble telescope is the most detailed image ever taken with visible light from the farthest distance. Many Hubble observations have led to many groundbreaking results in the field of astrophysics, such as the most precisely calculated rate of the expansion of the universe.

        HUT is the only telescope designed to be maintained in space by astronauts. Five maintenance flights were carried out, the last of which was in May 2009. The first shuttle flight was carried out in December 1993 to correct Hubble's imaging error. During maintenance flights 2, 3A and 3B, many subsystems were repaired and many observation devices were replaced with more modern and competent ones. However, after the accident of the Space Shuttle Columbia in 2003, the fifth maintenance flight was canceled for safety reasons. After long discussions, NASA reconsidered its decision and the agency's administrator, Mike Griffin, decided to conduct a shuttle flight for the last time. STS-125 took place in May 2009; Two new devices were installed and numerous repairs were made. New devices and fixes were tested and HUT resumed routine operations in September 2009.

        HUT is expected to operate until the James Webb Space Telescope (JWUT), the successor of HUT, which is planned to be sent into space in 2021 after the maintenance performed on the last flight, starts operating. (JWUT) will have a superior astronomical research program in many respects, but because it will observe in the infrared, it will complement (not replace) Hubble's ability to observe at the visible and ultraviolet scales of the spectrum.
        """),
    ActiveProgramsModel(programsName: "International Space Station", image: "international", title: """
        The International Space Station (ISS, English: International Space Station (ISS)) is a space base placed in low Earth orbit, in other words, a habitable artificial satellite. The first part of the station, which was built by combining modules, was launched in 1998. The structure of the station basically consists of pressurized modules, supporting exoskeleton and solar panels. It is the largest artificial satellite in Earth orbit. It can be seen with the naked eye when viewed from the earth at suitable times.

        The ISS is a laboratory center that provides a space environment and low gravity environment for experiments. It allows the crew to conduct experiments in biology, physiology, physics, chemistry, astronomy, meteorology and more. The station also provides a very suitable environment for the equipment and systems planned to be used in Moon and Mars missions to be tested in space before use.

        The station, which holds the record for the longest uninterrupted human presence in space, has accommodated space crew for 8,518 days uninterruptedly since the Discovery 1 shuttle arrived at the station on November 2, 2000, and continues to do so. The previous record was held by the Soviet space station Mir with 3644 days. As of January 2024, 276 people from 22 countries have visited the space station.

        The International Space Station program is a joint project by five participating space agencies, including the U.S. National Aeronautics and Space Administration, the Russian Federal Space Agency, the Japan Aerospace Exploration Agency, the European Space Agency, and the Canadian Space Agency. Ownership and usage rights of the station are determined by intergovernmental agreements and contracts. The station consists of two parts: the Russian Orbital Sector and the United States Orbital Sector. The orbital altitude of the station varies between 330 km and 435 km. The station uses the engines of the Zvezda module or visiting spacecraft to increase its altitude, which decreases over time. It makes 15.5 trips around the Earth in one day.

        As a result of the US budget increase, the station's term of office was extended from 2020 to 2024, and it is possible that it will be extended to 2028. It is not yet clear whether countries such as Russia, Germany, France, Japan and Canada, which currently support the project and have announced that they will support the project until 2020, will contribute to this extended budget. The Russian Federal Space Agency has made a proposal to build a new station called OPSEK, using the International Space Station before its retirement. ISS is the ninth station to accommodate personnel built to date. Russia announced that it will leave the International Space Station after 2024.

        NASA announced in January 2022 that the ISS's lifespan will be extended until January 2031, after which it is planned to deorbit using the deorbit module and redirect the remains to a remote region of the South Pacific Ocean.
        """),
    ActiveProgramsModel(programsName: "Kepler", image: "kepler", title: """
        The Kepler space telescope is a defunct space telescope launched by NASA in 2009 to discover Earth-sized planets orbiting other stars. Named after astronomer Johannes Kepler, the spacecraft was placed in a heliocentric orbit following the Earth. The principal investigator was William J. Borucki. The telescope's reaction control system (RCS) ran out of fuel after nine and a half years of operation, and NASA announced its decommissioning on October 30, 2018.

        Kepler is designed to scan part of the Earth region of the Milky Way to discover Earth-sized exoplanets in habitable zones and to estimate how many of the billions of stars in the Milky Way have such planets. Kepler's only scientific instrument was a photometer that continuously monitored the brightness of approximately 150,000 main sequence stars in a fixed field of view. This data was transmitted to Earth and analyzed to detect periodic dimming caused by planets passing in front of their parent stars. Only planets whose orbits were seen sideways from Earth could be detected. As of June 16, 2023, Kepler has observed 530,506 stars and detected 2,778 confirmed exoplanets.
        """),
    ActiveProgramsModel(programsName: "MESSENGER", image: "messenger", title: """
        MESSENGER (which stands for MErcury Surface, Space ENvironment, GEochemistry and Ranging) was a NASA robotic space probe that orbited the planet Mercury between 2011 and 2015 and studied Mercury's chemical composition, geology, and magnetic field. It passed by the planet in January 2008, becoming the second spacecraft to reach Mercury after Mariner 10.[11] The probe passed by the planet in October 2008 and September 2009, and became the first spacecraft to enter Mercury orbit on March 18, 2011. Entering orbit around Mercury is difficult as a spacecraft coming directly from Earth would be affected by the Sun's gravity and pass by the planet at a speed too fast to enter Mercury's orbit.

        MESSENGER passed by Earth once, Venus twice, and Mercury three times, gathering information. The instruments of the spacecraft, which entered Mercury orbit on March 18, 2011, were restarted on March 24, and the first photographs were returned on March 29. Scientific data collection started on April 4. The MESSENGER Space Probe crashed into the surface of Mercury on April 30, 2015.
        """),
    ActiveProgramsModel(programsName: "New Horizons", image: "horizons", title: """
        New Horizons is an unmanned spaceflight mission operated by NASA. It is the first spacecraft to fly to the dwarf planet Pluto and its moons. It was successfully launched on January 19, 2006. Passing by Jupiter on February 28, 2007 at 5:43:40 UTC, New Horizons passed closest to Pluto in July 2015 and examined the planet's structure and atmosphere before leaving the Solar System. Additionally, some of the ashes of Pluto's explorer Clyde Tombaugh are inside this unmanned spacecraft. The spacecraft New Horizon woke up from standby mode on December 6, 2014 and sent a signal to Earth.

        As of April 2015, the New Horizons satellite sent low-resolution images of Pluto and refreshed our information. The New Horizons satellite can be viewed full-time on NASA's official website, and the images it sent to Pluto from a distance of 12,500 km on July 14, 2015 were watched on the National Geographic Channel on July 14, 2015. On July 14, 2015, Google prepared a special doodle for New Horizons. .

        After sending all the images it took of Pluto to Earth, New Horizons is on its way to the Kuiper Belt. It is aimed to arrive in the Kuiper Belt on approximately November 1, 2019. As with Voyager 1, Voyager 2, Pioneer 10 and Pioneer 11, it has completed its first missions and continues its mission outside the Solar System.
        """),
    ActiveProgramsModel(programsName: "Spitzer Space Telescope", image: "spitzer", title: """
        The Spitzer Space Telescope (SST) (formerly known as the Infrared Space Telescope Facility, SIRTF) was an infrared space telescope launched into space in 2003 and retired on January 30, 2020.

        The $720 million Spitzer[3] was launched from Cape Canaveral SLC-17B on a Delta II 7920H rocket at 05.35.39 UTC on 25 August 2003.[4] The planned mission duration before the launch was set at 2.5 years, with the expectation that it could extend to five or more years until the liquid helium supply was exhausted. This period expired on May 15, 2009. Without the liquid helium needed to cool the telescope to very low temperatures, most instruments would not be usable. Despite this, the IRAC camera's two shortwave modules continued to operate with the same sensitivity as before the coolant was consumed and were used until early 2020 as the Spitzer Warm Mission. During the warm mission, IRAC's two short wavelength channels were estimated to operate at 30 K, experiencing little or no degradation compared to the nominal mission.
        """),
    ActiveProgramsModel(programsName: "James Webb", image: "jameswebb", title: """
        The James Webb Space Telescope (English: James Webb Space Telescope, abbreviated as JWST) is a space telescope for infrared astronomy. It is the most powerful telescope sent into space. Planned as a partial successor to the aging Hubble Space Telescope, it was developed under the leadership of NASA and with support from ESA and CSA. It was launched in December 2021 and entered orbit in January 2022.

        Named after James E. Webb, NASA's director of the Apollo program in 2002, JWST is an infrared telescope equipped with a 6.5-meter-wide gold-plated mirror. This mirror enables him to see 13.5 billion light years away, that is, when the first stars of the universe were formed.

        JWST is a project carried out jointly by 15 different states, the European Space Agency and the Canadian Space Agency, under the chairmanship of NASA. Tuned to observe infrared light, this 6.5-meter telescope is placed in orbit almost 1.5 million kilometers from Earth. This distance is four times the distance between the Earth and the Moon.

        Designed as a successor to Hubble in 1995, JWST took a long time to complete and encountered many technical obstacles. When it was launched on December 25, 2021, it was in a tight orbit around the L2 (Lagrange point 2) location, far from the Sun, 1.5 million kilometers beyond the Earth's orbit. The L2 position is the place in space where the gravity of the Sun and the Earth work together to pull an object orbiting the Sun at the same rate as the Earth, allowing it to complete one orbit in a year. So JWST is largely in Earth's shadow; This avoids heat pollution from the Sun and enables the telescope to detect very faint infrared sources in deep space. NASA claims that the telescope can even detect the heat of a bumblebee on the Moon.
        """),
    ActiveProgramsModel(programsName: "InSight", image: "insight", title: """
        InSight (Interior Exploration Using Seismic Investigations, Geodesy and Heat Transport) was a robotic lander designed to examine the deep interior of the planet Mars. It was manufactured by Lockheed Martin Space, managed by NASA's Jet Propulsion Laboratory (JPL), and most of its scientific instruments were produced by European agencies. The mission was launched on an Atlas V-401 launch vehicle at 11:05:01 UTC on May 5, 2018, and successfully landed on Elysium Planitia on Mars at 19:52:59 UTC on November 26, 2018. InSight operated on Mars for 1440 sols (1480 days; 4 years, 19 days).

        InSight's goals were to place a seismograph called the "Seismic Experiment for Interior Structure" (SEIS) on the surface of Mars to measure seismic activity and provide accurate 3D models of the planet's interior. Additionally, internal heat transfer was measured using a heat sensor called "Heat Flow and Physical Properties Package" (HP3) to study the early geological evolution of Mars. This was intended to provide new understanding of how the Solar System's terrestrial planets (Mercury, Venus, Earth, Mars) and Earth's satellite Moon formed and developed.

        The lander was planned to be launched in March 2016. But before launch, a persistent vacuum leak in the CNES-supplied seismograph, known as SEIS, caused NASA to postpone the planned launch to May 2018. When InSight was delayed, the remainder of the spacecraft was returned to Lockheed Martin. The problem that occurred in the seismograph during the waiting was resolved, but the cost of 675 million dollars increased to 830 million dollars. With the reuse of the technology in the Phoenix spacecraft, which successfully landed on Mars in 2008, the risks of the mission and the cost of the mission were reduced.

        NASA stated that they plan to put InSight in low-power mode to detect seismic events in July 2022 and continue monitoring the lander throughout the operational period ending in December 2022, as excessive dust accumulated on the solar panels prevented the vehicle from recharging. On December 20, 2022, it was announced that the InSight lander lost communication with Earth on December 15, 2022. It was announced that the mission ended on December 21, 2022
        """),
    ActiveProgramsModel(programsName: "Parker Solar Probe", image: "parker", title: """
        Parker Solar Probe (abbreviated PSP; formerly Solar Probe, Solar Probe Plus, or Solar Probe+), is a NASA Space Probe launched in 2018 with a mission to observe the Sun's outer corona. It will approach 9.86 solar radii (6.9 million km or 4.3 million miles) from the center of the Sun, and by 2025 its closest will be 430,000 mph (690,000 km/h), or 10% of the speed of light. It will be 0.064.

        The project was announced in 2009. The cost of the project is 1.5 billion US dollars. The Johns Hopkins University Applied Physics Laboratory designed and built the spacecraft, which was launched on August 12, 2018. It became the first NASA spacecraft named after a living person, honoring physicist Eugene Newman Parker, professor emeritus at the University of Chicago.

        A memory card containing the names of more than 1.1 million people was mounted on a plate and placed under the spacecraft's antenna on May 18, 2018. The card also includes photographs of Parker and a copy of his 1958 scientific paper predicting important aspects of solar physics.
        """),
    ActiveProgramsModel(programsName: "OSIRIS-REx", image: "osiris", title: """
        OSIRIS-REx was a NASA asteroid study and sample return mission that visited and collected samples from 101955 Bennu, a near-Earth carbonaceous asteroid. The material, brought back in September 2023, is expected to enable scientists to learn more about the formation and evolution of the Solar System, the early stages of planet formation, and the source of organic compounds that led to the formation of life on Earth. After the completion of the main mission, the spacecraft is planned to make a close pass to the asteroid 99942 Apophis, named OSIRIS-APEX.

        OSIRIS-REx was launched on September 8, 2016, passed by Earth on September 22, 2017, and arrived at Bennu on December 3, 2018. He then analyzed the surface for the next two years to find a suitable place to extract samples. On December 12, 2019, NASA announced the first sample collection site, known as Nightingale.[15] Surface landing and sample collection occurred at 22.12 UTC on October 20, 2020. OSIRIS-REx departed Bennu on May 10, 2021 and returned the sample to Earth on September 24, 2023. He then began his new mission to study 99942 Apophis. The spacecraft will arrive at Apophis in April 2029, when the asteroid is expected to approach Earth.

        101955 Bennu was chosen as the target of the study because it is a "time capsule" from the birth of the Solar System. Bennu has a very dark surface and is classified as a B-type asteroid, a subtype of carbonaceous C-type asteroids. Such asteroids are considered "primitive" because they have undergone little geological change since the time of their formation. In particular, Bennu was chosen due to the presence of pristine carbonaceous material, a key element in organic molecules necessary for life and representative of matter before the formation of the Earth. Organic molecules such as amino acids have previously been found in meteorite and comet samples, indicating that some components necessary for life can be synthesized naturally in space.

        The cost of the OSIRIS-REx mission is approximately US$800 million, excluding the Atlas V launch vehicle cost of US$183.5 million. The OSIRIS-APEX extended mission brought an additional cost of 200 million US dollars. It is the third planetary science mission selected under the New Frontiers program, after Juno and New Horizons, and the principal investigator is Dante Lauretta from the University of Arizona. OSIRIS-REx became the first United States spacecraft to return a sample from an asteroid. A similar Japanese space probe, Hayabusa, previously returned samples from 25143 Itokawa in 2010, and Hayabusa2, 162173 Ryugu, in December 2020.
        """),
    ActiveProgramsModel(programsName: "Perseverance", image: "perseverance", title: """
        Perseverance is an automobile-sized Mars rover designed to explore the Jezero crater on Mars as part of NASA's Mars 2020 mission. It was produced by the Jet Propulsion Laboratory and launched on July 30, 2020 at 11:50 UTC. Confirmation that the rover successfully landed on Mars was received on February 18, 2021 at 20:55 UTC. As of February 27, 2024, Perseverance has been active on Mars for 1,074 sols (1,104 Earth days or 3 years, 8 days) since landing. Following the rover's arrival, NASA named the landing site the Octavia E. Butler Landing Site.

        Perseverance has a similar design to its predecessor, Curiosity, but is moderately more advanced. It carries seven primary payload devices, nineteen cameras and two microphones.
        
        The rover also carried to Mars the mini-helicopter Ingenuity, an experimental technology test platform that performed the first powered aircraft flight on another planet on April 19, 2021. Damage to one or more rotor blades of the helicopter, which made its 72nd and final flight on January 18, 2024 (UTC), caused NASA to remove the helicopter from service.

        The rover's goals include identifying very old Martian environments that could support life, searching for evidence of ancient microbial life existing in these environments, collecting rock and soil samples for storage on the Martian surface, and testing oxygen production from the Martian atmosphere in preparation for future crewed missions.
        """),
    ActiveProgramsModel(programsName: "Juno", image: "juno", title: """
        Juno is a NASA space probe orbiting the planet Jupiter. It is manufactured by Lockheed Martin and operated by NASA Jet Propulsion Laboratory (JPL). The spacecraft was launched from Cape Canaveral Space Force Base on August 5, 2011, as part of the New Frontiers program.[6] Juno entered polar orbit of Jupiter on July 5, 2016, to begin its scientific exploration of the planet. After completing its mission, it will be deliberately deorbited into Jupiter's atmosphere.

        Juno's mission is to measure Jupiter's composition, gravitational field, magnetic field, and polar magnetosphere. It will also look for clues about how the planet formed, including whether it had a rocky core, the amount of water in the deep atmosphere, its mass distribution, and its deep winds, which can reach speeds of 620 km/h.
        
        Juno is the second spacecraft to orbit Jupiter, after the nuclear-powered Galileo orbiter, which orbited from 1995 to 2003. Unlike all previous spacecraft sent to the outer planets, Juno is powered by solar panels, which are commonly used by satellites orbiting the Earth and operating in the inner Solar System, while radioisotope thermoelectric generators are often used for missions to the outer Solar System and beyond. However, the three solar panel blades used for Juno, the largest ever installed on a planetary probe, play an integral role in stabilizing the spacecraft and generating power.
        """)
    ]
}
